### ISSUE TITLE
Unable to use cmdlets when -UseWindowsAuthentication is used for Set-VSTeamAccount

### ISSUE THREAD

**Issue by ChrisGibson1982** [DarqueWarrior/vsteam#403] opened 2021-07-09 13:16 UTC
Steps to reproduce
------------------

```powershell

Set-VSTeamAccount -Account $devOpsOrg -UseWindowsAuthentication
get-vsteam -ProjectName $myProjectName

Get-VSTeam: Cannot validate argument on parameter 'ProjectName'. The cmdlet cannot protect plain text secrets sent over unencrypted connections. To suppress this warning and send plain text secrets over unencrypted networks, reissue the command specifying the AllowUnencryptedAuthentication parameter

```

Expected behavior
-----------------

Should return a list of projects

Actual behavior
---------------

Should return a list of projects, but almost every command comes up with the same error in PowerShell 7.  Windows PowerShell just doesn't return anything

Environment data
----------------

OS

- [ ] macOS
- [X ] Windows
- [ ] Linux

Server

- [ ] TFS 2017
- [ ] TFS 2018
- [ ] Azure DevOps Server
- [ X] Azure DevOps Service

```powershell
> Get-VSTeamAPIVersion
Name                           Value
----                           -----
Packaging                      3.0-preview
Version                        TFS2017
ServiceEndpoints               3.0-preview
HierarchyQuery
Graph
Pipelines
TaskGroups                     3.0-preview
ExtensionsManagement           3.0-preview
Git                            3.0
VariableGroups
Core                           3.0
Release                        3.0-preview
DistributedTaskReleased
MemberEntitlementManagement
Tfvc                           3.0
Processes
Policy                         3.0
Build                          3.0
DistributedTask                3.0-preview
```

**Comment by SebastianSchuetze** [comment] 2021-07-13 10:34
I see that you are using the module version TFS2017 for the API but you are saying you try to go against Azure DevOps Services. The parameter `UseWindowsAuthentication` is only working against on-premises installations of Azure DevOps or in this case TFS. It does not work with the SaaS solution.

So this is by design and not a bug. :-)

closing this issue.

**Closed as completed by SebastianSchuetze** 2021-07-13 10:34 UTC
