### ISSUE TITLE
Get-VSTeamServiceEndpoint returns The type initializer for 'VSTeamProjectCache' threw an exception

### ISSUE THREAD

**Issue by andreimoraru** [DarqueWarrior/vsteam#160] opened 2019-05-16 12:44 UTC
Steps to reproduce
------------------

```powershell
PS C:\Users\newuser> Get-VSTeamServiceEndpoint -ProjectName projectname
```

Expected behavior
-----------------

```powershell
PS C:\Users\newuser> Get-VSTeamServiceEndpoint -ProjectName projectname
Name                                                               Type      ID                                   Created By
----                                                               ----      --                                   ----------
Endpoint1                                               azurerm   12345678-a098-4466-bd46-8857dfa28087 newuser
Endpoint2                                               azurerm   12345678-f90a-4a8b-9622-8d0f18ecab65 anotheruser
```

Actual behavior
---------------

```powershell
The type initializer for 'VSTeamProjectCache' threw an exception.
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\6.2.1\Private\common.ps1:334 char:9
+    if($([VSTeamProjectCache]::timestamp) -ne (Get-Date).Minute) {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException
 
Exception setting "projects": "The type initializer for 'VSTeamProjectCache' threw an exception."
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\6.2.1\Private\common.ps1:336 char:7
+       [VSTeamProjectCache]::projects = $arrSet
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
Exception setting "timestamp": "The type initializer for 'VSTeamProjectCache' threw an exception."
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\6.2.1\Private\common.ps1:337 char:7
+       [VSTeamProjectCache]::timestamp = (Get-Date).Minute
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
The type initializer for 'VSTeamProjectCache' threw an exception.
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\6.2.1\Private\common.ps1:334 char:9
+    if($([VSTeamProjectCache]::timestamp) -ne (Get-Date).Minute) {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException
 
Exception setting "projects": "The type initializer for 'VSTeamProjectCache' threw an exception."
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\6.2.1\Private\common.ps1:336 char:7
+       [VSTeamProjectCache]::projects = $arrSet
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
Exception setting "timestamp": "The type initializer for 'VSTeamProjectCache' threw an exception."
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\6.2.1\Private\common.ps1:337 char:7
+       [VSTeamProjectCache]::timestamp = (Get-Date).Minute
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```

Environment data
----------------

$VSTeamVersionTable
```powershell
> Get-VSTeamAPIVersion
Name                           Value
----                           -----
ServiceFabricEndpoint          5.0-preview
Build                          5.0
ExtensionsManagement           5.1-preview
Release                        5.1-preview
Version                        VSTS
MemberEntitlementManagement    5.1-preview
Packaging                      5.1-preview
Tfvc                           5.0
Git                            5.1-preview
Core                           5.0
Graph                          5.1-preview
DistributedTask                5.0-preview
```

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by DarqueWarrior** [comment] 2019-05-16 18:32
I will investigate today.

**Comment by DarqueWarrior** [comment] 2019-05-16 20:42
Everything is working as expected for me.  

My API Version is the same:
```PowerShell

Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
ServiceFabricEndpoint          5.0-preview                                                                                                                                                                                          
Build                          5.0                                                                                                                                                                                                  
ExtensionsManagement           5.1-preview                                                                                                                                                                                          
Release                        5.1-preview                                                                                                                                                                                          
Version                        VSTS                                                                                                                                                                                                 
MemberEntitlementManagement    5.1-preview                                                                                                                                                                                          
Packaging                      5.1-preview                                                                                                                                                                                          
Tfvc                           5.0                                                                                                                                                                                                  
Git                            5.1-preview                                                                                                                                                                                          
Core                           5.0                                                                                                                                                                                                  
Graph                          5.1-preview                                                                                                                                                                                          
DistributedTask                5.0-preview                                                                                                                                                                                          
```

My Version of PowerShell is a little different 
```PowerShell

Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
PSVersion                      5.1.17763.503                                                                                                                                                                                        
PSEdition                      Desktop                                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                              
BuildVersion                   10.0.17763.503                                                                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                  
SerializationVersion           1.1.0.1                                                                                                                                                                                              
```

**Comment by DarqueWarrior** [comment] 2019-05-16 23:25
Can you share more details that might help with duplicating it.

**Comment by andreimoraru** [comment] 2019-05-20 21:29
I can't reproduce it either
````powershell
 Get-VSTeamAPIVersion

Name                           Value
----                           -----
ServiceFabricEndpoint          5.0-preview
Build                          5.0
ExtensionsManagement           5.1-preview
Release                        5.1-preview
Version                        VSTS
MemberEntitlementManagement    5.1-preview
Packaging                      5.1-preview
Tfvc                           5.0
Git                            5.1-preview
Core                           5.0
Graph                          5.1-preview
DistributedTask                5.0-preview
````
````powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
````

**Comment by DarqueWarrior** [comment] 2019-06-01 13:56
Because you can no longer reproduce the issue I will close this one. If you see this again and can reproduce it please log new issue.

**Closed by DarqueWarrior** 2019-06-01 13:56 UTC

**Comment by bytejunkie** [comment] 2019-09-16 12:48
I've seen this issue this afternoon and managed to clear it by restarting VS Code.

**Comment by DarqueWarrior** [comment] 2019-09-24 13:16
That is interesting. I was not testing in the terminal of VS Code. I was using proper PowerShell console. Hmm. Thanks for commenting. If this pops up again will have to see if it is doing this everywhere or just in VS Code terminal.
