### ISSUE TITLE
Get-VSTeamBuildDefinition PropertyNotFoundException

### ISSUE THREAD

**Issue by jeremytbrun** [DarqueWarrior/vsteam#216] opened 2019-11-04 18:55 UTC
Steps to reproduce
------------------

```powershell
Set-VSTeamAccount -PersonalAccessToken *************************************************
Get-VSTeamBuildDefinition -ProjectName *********
```

Expected behavior
-----------------

```none
Lists all build definitions for project specified.
```

Actual behavior
---------------

```none
Displays the following error.

PropertyNotFoundException: ...\PowerShell\Modules\VSTeam\6.3.6\vsteam.classes.ps1
Line |
 312 |    ) : base($obj.name, $obj.id, $Projectname) {
     |                                               ^ The property 'name' cannot be found on this object. Verify that the property exists.
```

Environment data
----------------

OS

- [ ] macOS
- [X ] Windows
- [ ] Linux

Server

- [ ] TFS 2017
- [ ] TFS 2018
- [ ] Azure DevOps Server
- [X ] Azure DevOps Service

```powershell
> Get-VSTeamAPIVersion
Name                           Value
----                           -----
ServiceFabricEndpoint          5.0-preview
Git                            5.1-preview
Packaging                      5.1-preview
ExtensionsManagement           5.1-preview
DistributedTask                5.0-preview
Graph                          5.1-preview
Release                        5.1-preview
MemberEntitlementManagement    5.1-preview
VariableGroups                 5.0-preview.1
Version                        AzD
Core                           5.0
Tfvc                           5.0
Build                          5.0
```

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by DarqueWarrior** [comment] 2019-11-09 16:35
Are the build definitions you are trying to list YAML based?

**Comment by DarqueWarrior** [comment] 2019-11-09 18:37
This is a duplicate of #198 Cannot list build definitions. Will close this and continue to work the other.

**Closed by DarqueWarrior** 2019-11-09 18:37 UTC
Labels: duplicate

**Comment by jeremytbrun** [comment] 2019-11-10 13:26
> Are the build definitions you are trying to list YAML based?

It's a mixed bag. Some are YAML some are GUI. I should test which ones throw the error. I hadn't thought of separating them out like that.
