### ISSUE TITLE
Add-VSTeamWorkItem fails if project is beyond the first 100 projects.

### ISSUE THREAD

**Issue by jackfruhecolab** [DarqueWarrior/vsteam#444] opened 2022-01-31 13:48 UTC
Steps to reproduce
------------------

```powershell
get-vsteamproject -id "myproject" #works
add-vsteamworkitem -title "test" -workitemType "task" -parentid 123 -project "myproject" #fails 
Cannot validate argument on parameter 'Projectname'. 'myproject' is invalid
```

Expected behavior
-----------------

```
expected to work.

```

Actual behavior
---------------

```does not work

```

Environment data
----------------

OS

- [ ] macOS
- [ x] Windows
- [ ] Linux

Server

- [ ] TFS 2017
- [ ] TFS 2018
- [ ] Azure DevOps Server
- [ x] Azure DevOps Service

$vstermverstiontable is empty

```powershell
> Get-VSTeamAPIVersion
Billing                     : 5.1-preview.1
Build                       : 5.1
Core                        : 5.1
DistributedTask             : 6.0-preview
DistributedTaskReleased     : 5.1
ExtensionsManagement        : 6.0-preview
Git                         : 5.1
Graph                       : 6.0-preview
HierarchyQuery              : 5.1-preview
MemberEntitlementManagement : 6.0-preview
Packaging                   : 6.0-preview
Pipelines                   : 5.1-preview
Policy                      : 5.1
Processes                   : 6.0-preview
Release                     : 5.1
ServiceEndpoints            : 5.0-preview
TaskGroups                  : 6.0-preview
Tfvc                        : 5.1
VariableGroups              : 5.1-preview.1
Version                     : AzD
```

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#Special Note:
I see a constant theme in the VSTeam commands:
If there are more than 100 projects, and the project being worked on is past the first 100, the command fails.
I can only assume that the PS commands call the API to fetch a project list, which returns the first 100, and then the PS command filters from there.

Get-VSTeamProject -ID "projectname" works, and returns a bunch of info including the GUID of the project and the URL 

Is there a way that all these commands impacted by the 100 limit could optionally take $project.id or $project.url (and have the cmdlet use that to directly address the project instead of pulling the list of projects and then filtering?)

**Comment by SebastianSchuetze** [comment] 2022-02-01 09:05
Hi @jackfruhecolab please try `Set-VSTeamDefaultProjectCount -Count 500` before calling any function that is using a project specific parameter.

It is not a bug. We try to prefill the project list when using the project parameter. And this is by default 100. So if you have more, then you need to set the new limit beforehand.

**Comment by SebastianSchuetze** [comment] 2022-02-04 07:33
Hi @jackfruhecolab does this hint fixes it for you? I would close it for now and also  the other one since it is the same solution.

If you still have problems you can comment on it and we will check again.

**Closed as completed** 2022-02-04 07:33 UTC
