### ISSUE TITLE
Get-VSTeamGroup not return all groups

### ISSUE THREAD

**Issue by Alexlofern** [DarqueWarrior/vsteam#331] opened 2020-06-04 16:12 UTC
Some groups was not return on the list when you try get all.

I need to force with descriptor to get this groups informations.

**Comment by SebastianSchuetze** [comment] 2020-06-05 05:15
Hi @Alexlofern! Thanks for reporting.
Could you use our issue template to better describe the issue?

You can find the template here:
https://github.com/DarqueWarrior/vsteam/blob/master/.github/ISSUE_TEMPLATE.md

Otherwise, we maybe have not all the information we need.

**Comment by Alexlofern** [comment] 2020-06-05 14:00
Offcourse ....

### **Steps to reproduce**

First I'm Project Collection Administrator, have full access

Get-VSTeamGroup | Sort PrincipalName

### **Expected behavior**

Display all groups from all Azure DevOps Account

### **Actual behavior**

Considere that I have a project with name "ALM", so:

**[ALM]\ALM Team (not displayed)**
[ALM]\Build Administrators
**[ALM]\Contributors (not displayed)**
[ALM]\Consultoria
[ALM]\Deployment Group Administrators
[ALM]\Endpoint Administrators
[ALM]\Endpoint Creators
[ALM]\Operação
[ALM]\Project Administrators
[ALM]\Project Valid Users
[ALM]\Readers
**[ALM]\Release Administrators (not displayed)**

I have around 36 projects, some of the projects are displaying everything, others not 

Environment data

Windos 10 19041.264
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by DarqueWarrior** [comment] 2020-06-07 17:37
I just ran some tests and everything is working as expected.

```powershell
R:\repos\vsteam [master ≡]> Get-VSTeamGroup | Sort-Object PrincipalName 

PrincipalName                                          Name                                      ProjectName     Origin
-------------                                          ----                                      -----------     ------
[BlackShirt]\Project Collection Administrators         Project Collection Administrators         BlackShirt      vsts
[BlackShirt]\Project Collection Build Administrators   Project Collection Build Administrators   BlackShirt      vsts
[BlackShirt]\Project Collection Build Service Accounts Project Collection Build Service Accounts BlackShirt      vsts
[BlackShirt]\Project Collection Proxy Service Accounts Project Collection Proxy Service Accounts BlackShirt      vsts
[BlackShirt]\Project Collection Service Accounts       Project Collection Service Accounts       BlackShirt      vsts
[BlackShirt]\Project Collection Test Service Accounts  Project Collection Test Service Accounts  BlackShirt      vsts
[BlackShirt]\Project Collection Valid Users            Project Collection Valid Users            BlackShirt      vsts
[BlackShirt]\Security Service Group                    Security Service Group                    BlackShirt      vsts
[PeopleTracker]\Build Administrators                   Build Administrators                      PeopleTracker   vsts
[PeopleTracker]\Contributors                           Contributors                              PeopleTracker   vsts
[PeopleTracker]\Endpoint Administrators                Endpoint Administrators                   PeopleTracker   vsts
[PeopleTracker]\Endpoint Creators                      Endpoint Creators                         PeopleTracker   vsts
[PeopleTracker]\PeopleTracker Team                     PeopleTracker Team                        PeopleTracker   vsts
[PeopleTracker]\Project Administrators                 Project Administrators                    PeopleTracker   vsts
[PeopleTracker]\Project Valid Users                    Project Valid Users                       PeopleTracker   vsts
[PeopleTracker]\Readers                                Readers                                   PeopleTracker   vsts
[PeopleTracker]\Release Administrators                 Release Administrators                    PeopleTracker   vsts
[TEAM FOUNDATION]\Enterprise Invited Users             Enterprise Invited Users                  TEAM FOUNDATION vsts
[TEAM FOUNDATION]\Enterprise Service Accounts          Enterprise Service Accounts               TEAM FOUNDATION vsts
[Voting-App]\Build Administrators                      Build Administrators                      Voting-App      vsts
[Voting-App]\Contributors                              Contributors                              Voting-App      vsts
[Voting-App]\Deployment Group Administrators           Deployment Group Administrators           Voting-App      vsts
[Voting-App]\Endpoint Administrators                   Endpoint Administrators                   Voting-App      vsts
[Voting-App]\Endpoint Creators                         Endpoint Creators                         Voting-App      vsts
[Voting-App]\Project Administrators                    Project Administrators                    Voting-App      vsts
[Voting-App]\Project Valid Users                       Project Valid Users                       Voting-App      vsts
[Voting-App]\Readers                                   Readers                                   Voting-App      vsts
[Voting-App]\Release Administrators                    Release Administrators                    Voting-App      vsts
[Voting-App]\Voting-App Team                           Voting-App Team                           Voting-App      vsts


R:\repos\vsteam [master ≡]> Get-VSTeamGroup -ProjectName 'PeopleTracker'

PrincipalName                           Name                    ProjectName   Origin
-------------                           ----                    -----------   ------
[PeopleTracker]\Build Administrators    Build Administrators    PeopleTracker vsts
[PeopleTracker]\Endpoint Creators       Endpoint Creators       PeopleTracker vsts
[PeopleTracker]\Project Administrators  Project Administrators  PeopleTracker vsts
[PeopleTracker]\Contributors            Contributors            PeopleTracker vsts
[PeopleTracker]\PeopleTracker Team      PeopleTracker Team      PeopleTracker vsts
[PeopleTracker]\Endpoint Administrators Endpoint Administrators PeopleTracker vsts
[PeopleTracker]\Release Administrators  Release Administrators  PeopleTracker vsts
[PeopleTracker]\Readers                 Readers                 PeopleTracker vsts
[PeopleTracker]\Project Valid Users     Project Valid Users     PeopleTracker vsts


R:\repos\vsteam [master ≡]> Get-VSTeamGroup -ProjectName 'Voting-App'   

PrincipalName                                Name                            ProjectName Origin
-------------                                ----                            ----------- ------
[Voting-App]\Release Administrators          Release Administrators          Voting-App  vsts
[Voting-App]\Contributors                    Contributors                    Voting-App  vsts
[Voting-App]\Build Administrators            Build Administrators            Voting-App  vsts
[Voting-App]\Readers                         Readers                         Voting-App  vsts
[Voting-App]\Endpoint Administrators         Endpoint Administrators         Voting-App  vsts  
[Voting-App]\Project Administrators          Project Administrators          Voting-App  vsts
[Voting-App]\Voting-App Team                 Voting-App Team                 Voting-App  vsts
[Voting-App]\Deployment Group Administrators Deployment Group Administrators Voting-App  vsts
[Voting-App]\Endpoint Creators               Endpoint Creators               Voting-App  vsts
[Voting-App]\Project Valid Users             Project Valid Users             Voting-App  vsts
```

What version of the Module are you running? You can find it be running:

```PowerShell
c:\>Get-VSTeamInfo

Name                           Value
----                           -----
ModuleVersion                  6.5.0
Account                        https://dev.azure.com/BlackShirt
DefaultProject
Version                        VSTS
```

**Comment by Alexlofern** [comment] 2020-06-11 14:05
Not working for me and I don't know why ....

**Comment by Alexlofern** [comment] 2020-06-11 14:08
Sorry for ask again, do you have a project with more than one Team?

**Comment by Alexlofern** [comment] 2020-06-11 15:36
Name                           Value
----                           -----
ModuleVersion                  6.4.8
Account                        https://dev.azure.com/cc
DefaultProject
Version                        VSTS

**Comment by SebastianSchuetze** [comment] 2020-06-19 17:53
Hi same for me @Alexlofern . It works for me as well and I have multiple projects with multiple teams:

PS F:\repos\PR_github\vsteam\333> Get-VSTeamInfo

```
Name                           Value
----                           -----
DefaultProject
Version                        VSTS
ModuleVersion                  6.4.8
Account                        https://dev.azure.com/razorspoint-test

PS F:\repos\PR_github\vsteam\333> Get-VSTeamGroup | Sort-Object PrincipalName


PrincipalName                                                                                      Name
-------------                                                                                      ----
[AF-Test]\AF-Test Team                                                                             AF-Test Team
[AF-Test]\Build Administrators                                                                     Build Administrators   
[AF-Test]\Contributors                                                                             Contributors
[AF-Test]\Endpoint Administrators                                                                  Endpoint Administrators
[AF-Test]\Endpoint Creators                                                                        Endpoint Creators      
[AF-Test]\Project Administrators                                                                   Project Administrators 
[AF-Test]\Project Valid Users                                                                      Project Valid Users    
[AF-Test]\Readers                                                                                  Readers
[AF-Test]\Release Administrators                                                                   Release Administrators 
[AF-Test]\Team1                                                                                    Team1
[AF-Test]\Team2                                                                                    Team2
[My Test]\Build Administrators                                                                     Build Administrators   
[My Test]\Contributors                                                                             Contributors
[My Test]\My Team 2                                                                                My Team 2
[My Test]\My Team 3                                                                                My Team 3
[My Test]\My Test Team                                                                             My Test Team
[My Test]\Project Administrators                                                                   Project Administrators 
[My Test]\Project Valid Users                                                                      Project Valid Users    
[My Test]\Readers                                                                                  Readers
[MyProjectConnectionTest]\Build Administrators                                                     Build Administrators    
[MyProjectConnectionTest]\Contributors                                                             Contributors
[MyProjectConnectionTest]\Endpoint Administrators                                                  Endpoint Administrators 
[MyProjectConnectionTest]\Endpoint Creators                                                        Endpoint Creators       
[MyProjectConnectionTest]\MyProjectConnectionTest Team                                             MyProjectConnectionTes… 
[MyProjectConnectionTest]\Project Administrators                                                   Project Administrators 
[MyProjectConnectionTest]\Project Valid Users                                                      Project Valid Users     
[MyProjectConnectionTest]\Readers                                                                  Readers
[MyProjectConnectionTest]\Release Administrators                                                   Release Administrators  
[Pipeline Artifacts vs Build Artifacts]\Build Administrators                                       Build Administrators    
[Pipeline Artifacts vs Build Artifacts]\Contributors                                               Contributors
[Pipeline Artifacts vs Build Artifacts]\Pipeline Artifacts vs Build Artifacts Team                 Pipeline Artifacts vs … 
[Pipeline Artifacts vs Build Artifacts]\Project Administrators                                     Project Administrators  
[Pipeline Artifacts vs Build Artifacts]\Project Valid Users                                        Project Valid Users     
[Pipeline Artifacts vs Build Artifacts]\Readers                                                    Readers
[Pipeline Artifacts vs Build Artifacts]\Release Administrators                                     Release Administrators  
[razorspoint-test]\Organization Owner                                                              Organization Owner      
[razorspoint-test]\Project Collection Administrators                                               Project Collection Adm… 
[razorspoint-test]\Project Collection Build Administrators                                         Project Collection Bui…
[razorspoint-test]\Project Collection Build Service Accounts                                       Project Collection Bui… 
[razorspoint-test]\Project Collection Proxy Service Accounts                                       Project Collection Pro… 
[razorspoint-test]\Project Collection Service Accounts                                             Project Collection Ser… 
[razorspoint-test]\Project Collection Test Service Accounts                                        Project Collection Tes… 
[razorspoint-test]\Project Collection Valid Users                                                  Project Collection Val… 
[razorspoint-test]\Security Service Group                                                          Security Service Group  
[RP_Build-Release-AzurePolicy-IntegrationTests]\Build Administrators                               Build Administrators    
[RP_Build-Release-AzurePolicy-IntegrationTests]\Contributors                                       Contributors
[RP_Build-Release-AzurePolicy-IntegrationTests]\Endpoint Administrators                            Endpoint Administrators 
[RP_Build-Release-AzurePolicy-IntegrationTests]\Endpoint Creators                                  Endpoint Creators       
[RP_Build-Release-AzurePolicy-IntegrationTests]\Project Administrators                             Project Administrators  
[RP_Build-Release-AzurePolicy-IntegrationTests]\Project Valid Users                                Project Valid Users     
[RP_Build-Release-AzurePolicy-IntegrationTests]\Readers                                            Readers
[RP_Build-Release-AzurePolicy-IntegrationTests]\Release Administrators                             Release Administrators  
[RP_Build-Release-AzurePolicy-IntegrationTests]\RP_Build-Release-AzurePolicy-IntegrationTests Team RP_Build-Release-Azure… 
[TEAM FOUNDATION]\Enterprise Invited Users                                                         Enterprise Invited Use… 
[TEAM FOUNDATION]\Enterprise Service Accounts                                                      Enterprise Service Acc… 
[YAML Tests]\Build Administrators                                                                  Build Administrators    
[YAML Tests]\Contributors                                                                          Contributors
[YAML Tests]\Project Administrators                                                                Project Administrators  
[YAML Tests]\Project Valid Users                                                                   Project Valid Users     
[YAML Tests]\Readers                                                                               Readers
[YAML Tests]\Release Administrators                                                                Release Administrators  
[YAML Tests]\YAML Tests Team                                                                       YAML Tests Team
```

**Comment by SebastianSchuetze** [comment] 2020-06-19 17:59
I even tried to remove myself from the My Test project from all permission groups and teams. Still shows up as a global admin.

**Comment by SebastianSchuetze** [comment] 2020-07-02 18:11
@Alexlofern I gonna close this for now. If you can reproduce this with a different tenant so that we can see it, then we can investigate more. Up until now, we have not enough info to investigate more.

**Closed by SebastianSchuetze** 2020-07-02 18:11 UTC
Labels: Investigating
